// Full List of Do's (100 items)
const dos = [
  "Stargaze",
  "Knit",
  "Bake",
  "Picnic",
  "Puzzle",
  "Daydream",
  "Doodle",
  "Sketch",
  "Journal",
  "Brew",
  "Declutter",
  "Wander",
  "Tinker",
  "Photograph",
  "Garden",
  "Stretch",
  "Explore",
  "Collect",
  "Meditate",
  "Whittle",
  "Bike",
  "Paint",
  "Swim",
  "Calligraphy",
  "Camp",
  "Read",
  "Dance",
  "Sip",
  "Sculpt",
  "Map",
  "Build",
  "Arrange",
  "Stroll",
  "Pet",
  "Fold",
  "Originate",
  "Smile",
  "Sing",
  "Converse",
  "Collaborate",
  "Organize",
  "Hydrate",
  "Reflect",
  "Listen",
  "Recycle",
  "Donate",
  "Preserve",
  "Draw",
  "Frame",
  "Imagine",
  "Design",
  "Bounce",
  "Flip",
  "Test",
  "Cheer",
  "Carve",
  "Observe",
  "Investigate",
  "Write",
  "Solve",
  "Decorate",
  "Travel",
  "Paddle",
  "Sketch",
  "Rest",
  "Inspire",
  "Assist",
  "Repair",
  "Support",
  "Adapt",
  "Plant",
  "Craft",
  "Simplify",
  "Try",
  "Balance",
  "Refresh",
  "Grin",
  "Create",
  "Capture",
  "Embrace",
  "Preserve",
  "Imagine",
  "Build",
  "Laugh",
  "Spin",
  "Whisper",
  "Swing",
  "Reflect",
  "Cheer",
  "Dip",
  "Frame",
  "Observe",
  "Cook",
  "Savor",
  "Glimpse",
  "Breathe",
  "Taste",
  "Explore",
  "Learn",
  "Grow",
];

// Full List of Don'ts (100 items)
const donts = [
  "Overanalyze",
  "Hoard",
  "Overshare",
  "Critique",
  "Ruminate",
  "Gossip",
  "Postpone",
  "Interrupt",
  "Glorify",
  "Sulk",
  "Snap",
  "Linger",
  "Dwell",
  "Compare",
  "Overdo",
  "Self-blame",
  "Rush",
  "Obsess",
  "Underestimate",
  "Complicate",
  "Overindulge",
  "Underestimate",
  "Overreact",
  "Suppress",
  "Exaggerate",
  "Skip",
  "Delay",
  "Agitate",
  "Exclude",
  "Ignore",
  "Mislead",
  "Procrastinate",
  "Criticize",
  "Overthink",
  "Hoard",
  "Interrupt",
  "Panic",
  "Shout",
  "Neglect",
  "Complain",
  "Overspend",
  "Forget",
  "Overwhelm",
  "Waste",
  "Disturb",
  "Misjudge",
  "Misuse",
  "Underprepare",
  "Underestimate",
  "Exhaust",
  "Disrupt",
  "Force",
  "Overcommit",
  "Insist",
  "Impose",
  "Exploit",
  "Procrastinate",
  "Disrespect",
  "Overschedule",
  "Sulk",
  "Self-doubt",
  "Overexert",
  "Judge",
  "Overconsume",
  "Sabotage",
  "Withdraw",
  "Undervalue",
  "Dismiss",
  "Avoid",
  "Discredit",
  "Limit",
  "Underperform",
  "Skim",
  "Overstretch",
  "Suppress",
  "Skimp",
  "Distract",
  "Ignore",
  "Outdo",
  "Misplace",
  "Misstep",
  "Overshadow",
  "Delay",
  "Overwhelm",
  "Underestimate",
  "Interrupt",
  "Overschedule",
  "Misinterpret",
  "Skew",
  "Scatter",
  "Fluster",
  "Panic",
  "Self-blame",
  "Overprepare",
  "Rush",
  "Overconsume",
  "Compare",
  "Judge",
  "Agitate",
  "Resist",
];

// Seeded Shuffle Algorithm (Based on Date)
function seededShuffle(array, seed) {
  const result = [...array];
  let m = result.length,
    t,
    i;

  while (m) {
    i = Math.floor(random(seed) * m--);
    t = result[m];
    result[m] = result[i];
    result[i] = t;
    seed++;
  }

  return result;
}

// Generate a Random Number Based on a Seed
function random(seed) {
  const x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
}

// Get Today's Date as a Seed
function getDailySeed() {
  const today = new Date();
  return parseInt(
    `${today.getFullYear()}${today.getMonth() + 1}${today.getDate()}`,
    10
  );
}

// Get Daily Do's and Don'ts
export const getDailyDosAndDonts = () => {
  const seed = getDailySeed();
  const dailyDos = seededShuffle(dos, seed).slice(0, 3);
  const dailyDonts = seededShuffle(donts, seed + 100).slice(0, 3);
  return { dos: dailyDos, donts: dailyDonts };
};
