// utils.js
export const emotionColors = {
  admiration: "#FFD700", // Gold
  amusement: "#FF6347", // Tomato
  anger: "#FF0000", // Red
  annoyance: "#FF4500", // OrangeRed
  approval: "#32CD32", // LimeGreen
  autonomy: "#00BFFF", // DeepSkyBlue
  boredom: "#B0C4DE", // LightSteelBlue
  caring: "#98FB98", // PaleGreen
  confusion: "#D3D3D3", // LightGray
  creativity: "#FF1493", // DeepPink
  curiosity: "#00FFFF", // Aqua
  desire: "#DC143C", // Crimson
  disappointment: "#A9A9A9", // DarkGray
  disapproval: "#8B0000", // DarkRed
  disgust: "#228B22", // ForestGreen
  embarrassment: "#FFB6C1", // LightPink
  empty: "#DCDCDC", // Gainsboro
  enthusiasm: "#FFD700", // Gold
  excitement: "#FF4500", // OrangeRed
  fear: "#8B0000", // DarkRed
  fun: "#FF69B4", // HotPink
  gratitude: "#32CD32", // LimeGreen
  grief: "#708090", // SlateGray
  happiness: "#FFFF00", // Yellow
  hate: "#800000", // Maroon
  joy: "#FFFF00", // Yellow
  love: "#FF69B4", // HotPink
  meaning: "#800080", // Purple
  nervousness: "#FFFF00", // Yellow
  neutral: "#808080", // Gray
  optimism: "#FFD700", // Gold
  pride: "#8A2BE2", // BlueViolet
  realization: "#FFD700", // Gold
  recreation: "#32CD32", // LimeGreen
  relief: "#4682B4", // SteelBlue
  sadness: "#1E90FF", // DodgerBlue
  safety: "#2E8B57", // SeaGreen
  sense_of_belonging: "#FF6347", // Tomato
  surprise: "#FFD700", // Gold
  sustenance: "#8B4513", // SaddleBrown
  understanding: "#20B2AA", // LightSeaGreen
  worry: "#FF6347", // Tomato
};
